pipeline:
  name: docker-build
  identifier: dockerbuild
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: harnesstestbranch
        build: <+input>
  stages:
    - stage:
        name: docker image build
        identifier: docker_image_build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: https://index.docker.io/v1/
                    tags:
                      - app=nginx
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: aks
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
